version: '3'
services:
    reverseproxy:
        build:
            context: ./reverseproxy
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always
    
    #dbapp:
    #    image: mysql:5
    #    restart: always
    #    volumes:
    #        - db-volume:/var/lib/mysql
    #    env_file:
    #        - upgradetesting-docker/moodle_variables.env
    #    networks:
    #        - backendDB
    #    deploy:
    #        replicas: 1
    #        restart_policy:
    #            condition: any    
      
    tarnith.com:
        build:
            context: ./tarnith.com
            dockerfile: Dockerfile
        restart: always
        volumes:
            - /etc/letsencrypt/live/pbok.ca/fullchain.pem:/etc/nginx/fullchain.pem
            - /etc/letsencrypt/live/pbok.ca/cert.pem:/etc/nginx/cert.pem
            - /etc/letsencrypt/live/pbok.ca/privkey.pem:/etc/nginx/privkey.pem
        #    - /home/ec2-user/docker/reverseproxy-docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
        #    - 8080:80
            - 8080:443
        