version: '3'
services:
    reverseproxy:
        build:
            context: ./reverseproxy
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always
    
    tarnith.com:
        build:
            context: ./tarnith.com
            dockerfile: Dockerfile
        restart: always
        volumes:
            - cert:/
        ports:
        #    - 8080:80
            - 8080:443
        